openapi: 3.0.1
info:
  title: Greeting API
  version: 1.0.0
paths:
  /greet:
    post:
      description: API endpoint to generate a greeting message
      operationId: lambda_handler
      summary: Generate a friendly greeting
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  example: Hi there!
      responses:
        "200":
          description: Successful greeting
          content:
            application/json:
              schema:
                type: object
                properties:
                  body:
                    type: string

